version: '3.8'

services:
  fikrfree-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./main_index:/app/main_index
    restart: unless-stopped